# Generated by Django 3.2.15 on 2026-03-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_vendorconnectionconfig'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendorconnectionconfig',
            name='vendor_con_user_id_954529_idx',
        ),
        migrations.AddIndex(
            model_name='vendorconnectionconfig',
            index=models.Index(fields=['user', 'vendor', 'capability'], name='vendor_conn_user_id_85703d_idx'),
        ),
    ]
